(define (add a b)
    (+ a b)
  )
(define (halve x)
    (if (= 0 (remainder x 2))
        (/ x 2)
        (/ (- x 1) 2))
  )
(define (double x)
    (add x x)
    )
(define (fast_mul a b)
    (cond ((= b 0) 0)
          ((even? b) (fast_mul (double a) (halve b)))
          ((odd? b) (add a (fast_mul a (- b 1))))
          )
    )
