(define (find-divisor n test-divisor)
    (cond ((> (square test-divisor) n) n)
          ((divided? n test-divisor) test-divisor)
          (else (find-divisor n (next test-divisor)))
          )
    )
(define (next test-divisor)
    (if (= 2 test-divisor) 3
        (+ 2 test-divisor)
        )
    )
(define (divided? n divisor) 
     (= 0 (remainder n divisor)))

(define (prime? n)
     (= n (smallest-divisor n 2))
     )
(define (smallest-divisor n)
    (find-divisor n 2)
  )
